Fix: Spring 7 Webflux NoSuchElementError on HttpHeaders#entrySet()  (#4556)
* fix(webflux): fix NoSuchMethodError when using spring framework 7 with webflux

* fix(webflux): fix compilation

* fix(webflux): fix compilation errors + provide spring 7 testing module

* fix(webflux): fix comment

* fix(webflux): Specify allow method TRACE in the config

* fix(webflux): fix comments + fix discard subscription  on close

* fix(webflux): fix comments

* fix(webflux): add sub cancel instrumentation

* fix(webflux): fix sub cancel test

* fix(webflux): rem debug test logs

* fix(webflux): optimize inst name matcher

* fix(webflux): non-instrument solution

* Revert "fix(webflux): non-instrument solution"

This reverts commit 42f3bdd0eb5c54392699d96e6d029cceec232587.

* fix(webflux): header copy NPE on cancelled subscription

* fix(webflux): mod type matcher prefilter

---------

Co-authored-by: jihad540 <jihad.bouhaiji@tvh.com>
Co-authored-by: jackshirazi <jack.shirazi@elastic.co>